search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"

ignore_unused:
  - '{devise,kaminari,will_paginate}.*'
  - activerecord.*
  - date.*
  - simple_form.*
  - time.*'
  - helpers.submit.*
  - helpers.page_entries_info.*
  - errors.messages.*

data:
  read:
     - config/locales/%{locale}.yml
     - config/locales/*.%{locale}.yml