# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f2813ab458227fffb871578e90de7f2eb2569191ac903bde656de8b3cd8e350e33226cb5e78d1a9b2dbb58ecec487f78ac19994b79b7f98e1de9d494af7ade

test:
  secret_key_base: cabd78b6cc9b7da6137ddf31700b43a6bf9fdcafdd1ffdcd6160f7211217cdef462da0d2b34e32fc7f63d65fccbf6a3bebfeb660c1251f1b288b4f73f70301d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
